---
global:
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: services
    metrics_path: "/metrics"
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - 'tasks.demo_service_v1'
          - 'tasks.demo_service_v2'
        type: 'A'
        port: 2112
  - job_name: cadvisor
    metrics_path: /metrics
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: 'A'
        port: 8080
